version: "3"

services:
    mysql:
        image: mysql:5.7
        restart: always
        hostname: mysql
        container_name: mysql
        networks:
            - backend
        ports:
            - 3306:3306
        volumes:
            - /data/mysql/logs:/var/log/mysql
            - /data/mysql/datas:/var/lib/mysql
            - /data/mysql/backups:/backups
        environment:
            MYSQL_USER: test
            MYSQL_PASSWORD: N4F3ABaFui
            MYSQL_ROOT_PASSWORD: RZ3X5mh8LUqkWNSh

    php:
        image: myphp:v7.2
        restart: always
        hostname: php
        container_name: php
        networks:
            - backend
        ports:
            - 9000:9000
        volumes:
            - /data/www/zhongtujiance:/data/www

    nginx:
        image: nginx
        restart: always
        hostname: nginx
        container_name: nginx
        networks:
            - backend
        ports:
            - 80:80
        volumes:
            - /data/www/zhongtujiance:/data/www
            - /data/www/zhongtujiance/nginx/logs:/var/log/nginx
            - /data/www/zhongtujiance/nginx/config/conf.d:/etc/nginx/conf.d
            - /data/www/zhongtujiance/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - /data/www/zhongtujiance/nginx/config/includes:/etc/nginx/includes

networks:
    backend: